{ pkgs, ... }:
# NixOS system configuration.
# Apply: sudo nixos-rebuild switch --flake ~/.config/nix#$(nix eval --raw nixpkgs#stdenv.hostPlatform.system)
{
  imports = [
    # Machine-specific hardware config generated by the NixOS installer.
    # Provides fileSystems, swapDevices, and kernel modules — mirrors the
    # default configuration.nix behaviour.
    /etc/nixos/hardware-configuration.nix
  ];

  # Bootloader (matches NixOS installer default for EFI systems).
  boot.loader.systemd-boot.enable      = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Required by NixOS — records the state version the system was first installed with.
  system.stateVersion = "24.11";

  # Allow unfree packages (VS Code, Nvidia drivers, etc.)
  nixpkgs.config.allowUnfree = true;

  # --- system packages ---

  environment.systemPackages = with pkgs; [
    vim
    git
    curl
    brave
  ];

  # --- system settings ---

  networking.firewall.enable = true;
  services.openssh.enable    = true;

  # --- default terminal ---

  # Sets $TERMINAL system-wide so DEs, launchers, and scripts all open WezTerm.
  environment.variables.TERMINAL = "wezterm";

  # --- user ---

  users.users.kozaxo = {
    isNormalUser = true;
    shell        = pkgs.zsh;
    extraGroups  = [ "wheel" "docker" ];
  };

  # --- virtualisation ---

  virtualisation.docker.enable = true;

  virtualisation.podman = {
    enable            = true;
    dockerCompat      = false;  # set true to alias `podman` as `docker`
    defaultNetwork.settings.dns_enabled = true;
  };

  # --- gnome ---

  services.xserver = {
    enable                      = true;
    displayManager.gdm.enable   = true;
    desktopManager.gnome.enable = true;
  };

  # Remove pre-installed GNOME apps that are not needed.
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour
    gnome-connections
  ];

  # --- shell --- (must be enabled system-wide so NixOS writes /etc/shells)

  programs.zsh.enable = true;

  # --- home manager ---

  home-manager.useGlobalPkgs   = true;
  home-manager.useUserPackages = true;
  home-manager.users.kozaxo = {
    imports           = [ ./common/home.nix ./common/gnome.nix ];
    home.stateVersion = "24.11";
    # On NixOS the entire library graph is managed by Nix, so the nixpkgs
    # wezterm package works correctly (unlike on standalone Ubuntu).
    home.packages     = [ pkgs.vscode ];
  };
}
